### ISSUE TITLE
Breaks on Node, when using a component with useEffects()

### ISSUE THREAD

**Issue by stringparts** [preactjs/preact-render-to-string#200]
`renderToString()` returns and works as expected, but an exception is thrown asynchronously:

```
ReferenceError: cancelAnimationFrame is not defined
    at Timeout.r3 (.../node_modules/preact/hooks/src/index.js:251:3)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by stringparts** [comment]
Upgrading to latest (10.5.14) fixed it for me. Looks like the internal _skipEffects option is used to prevent running effects with renderToString().

Thank you!
