### ISSUE TITLE
Use preact render to string with htm

### ISSUE THREAD

**Issue by renhiyama** [preactjs/preact-render-to-string#231]
I dont want to use jsx file extension, therefore I had been using preact+htm for CSR till date. Today I thought of going SSR, but it looks like `render()` wont work with:
```js
h`<h1>test</h1>`;
```

Code to test out:
```js
let render = await Import("https://esm.sh/preact-render-to-string@5.2.0");
    let { h } = await Import("https://esm.sh/preact@10.10.0");
    console.log(h`<h1>failure</h1>`);
    console.log(render(h`<h1>Hello</h1>`));
```

Logs:
```js
{
  type: [ '<h1>failure</h1>' ],
  props: {},
  key: undefined,
  ref: undefined,
  __k: null,
  __: null,
  __b: 0,
  __e: null,
  __d: undefined,
  __c: null,
  __h: null,
  constructor: undefined,
  __v: 1
}
https://esm.sh/v87/preact-render-to-string@5.2.0/es2015/preact-render-to-string.js:7
`):i=U}if(i+=">",te.test(a))throw new Error(a+" is not a valid HTML tag name in "+i);var C,ie=ce.test(a)||r.voidElements&&r.voidElements.test(a),c=[];if(_)l&&j(_)&&(_=`
                                  ^

Error: <h1>Hello</h1> is not a valid HTML tag name in <<h1>Hello</h1>>
    at h (https://esm.sh/v87/preact-render-to-string@5.2.0/es2015/preact-render-to-string.js:7:35)
    at m (https://esm.sh/v87/preact-render-to-string@5.2.0/es2015/preact-render-to-string.js:3:684)
    at file:///home/user/coding/create-reeact-app/node_modules/reejs/server.js:28:17
```

**Comment by renhiyama** [comment]
Looks Like I found a fix:
```js
let SSRrender = await Import("https://esm.sh/preact-render-to-string@5.2.0");
    let { h, Component, render } = await Import("https://esm.sh/preact@10.10.0");
    let htm = await Import('https://unpkg.com/htm?module');
    let html = htm.bind(h);
    function App () {
        return html`<h1>Hello world!</h1>`;
      }
    console.log(SSRrender(html`<${App} />`));
```

It returns back: `<h1>Hello world!</h1>`  just as expected!

**Comment by marvinhagemeister** [comment]
Yup, the second variant is correct. The issue with the code in the original post is that it doesn't use `htm` at all. It just calls `h` from `preact` as if it would be `htm`, but it isn't. That's why it wasn't working.
