### ISSUE TITLE
Using @tanstack/react-query causes errors.

### ISSUE THREAD

**Issue by hato810424** [preactjs/preact-render-to-string#350]
I want to use `@tanstack/react-query` with `vite` + `preact`, but I noticed an error.

It is possible to work around this by disabling `react-query` on server rendering, e.g. with a custom Hook, but this is not a good implementation...🙁

```
"@tanstack/react-query": "^5.29.2",
"preact": "^10.20.2",
"preact-render-to-string": "^6.4.2",
"vite": "^5.2.9",
```

```javascript
// https://tanstack.com/query/v4/docs/framework/react/overview
// ↓↓↓ official example
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query'

const queryClient = new QueryClient()

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Example />
    </QueryClientProvider>
  )
}

function Example() {
  const { isLoading, error, data } = useQuery({
    queryKey: ['repoData'],
    queryFn: () =>
      fetch('https://api.github.com/repos/TanStack/query').then((res) =>
        res.json(),
      ),
  })

  if (isLoading) return 'Loading...'

  if (error) return 'An error has occurred: ' + error.message

  return (
    <div>
      <h1>{data.name}</h1>
      <p>{data.description}</p>
      <strong>👀 {data.subscribers_count}</strong>{' '}
      <strong>✨ {data.stargazers_count}</strong>{' '}
      <strong>🍴 {data.forks_count}</strong>
    </div>
  )
}
// ↑↑↑ official example

import { render } from 'preact-render-to-string'
render(<App></App>)

```

```
TypeError: Cannot read properties of null (reading 'useContext')
    at Module.useContext (.../node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1618:21)
    at useQueryClient (.../node_modules/.pnpm/@tanstack+react-query@5.29.2_react@18.2.0/node_modules/@tanstack/react-query/src/QueryClientProvider.tsx:11:24)
    at useBaseQuery (.../node_modules/.pnpm/@tanstack+react-query@5.29.2_react@18.2.0/node_modules/@tanstack/react-query/src/useBaseQuery.ts:47:18)
    at Module.useQuery (.../node_modules/.pnpm/@tanstack+react-query@5.29.2_react@18.2.0/node_modules/@tanstack/react-query/src/useQuery.ts:46:10)
    at Object.call (.../pages/index.tsx:78:38)
    at _renderToString (.../node_modules/.pnpm/preact-render-to-string@6.4.2_preact@10.20.2/node_modules/preact-render-to-string/src/index.js:360:22)
    at Module.S (.../node_modules/.pnpm/preact-render-to-string@6.4.2_preact@10.20.2/node_modules/preact-render-to-string/src/index.js:58:10)
```

**Comment by rschristian** [comment]
Try adding the [Node aliases](https://preactjs.com/guide/v10/getting-started/#aliasing-in-node) first, before  installing `@tanstack/query`

PNPM should support this, but test with NPM too.

**Comment by hato810424** [comment]
Thanks!!!!
I was so focused on the "vite" alias that I forgot that "dependencies" also has an alias function.

The error was resolved by running the following command
```
pnpm i react@npm:@preact/compat
pnpm i react-dom@npm:@preact/compat
```

**Comment by rschristian** [comment]
No problem!

It's definitely a surprise for most, that Vite won't use the configured aliases during SSR. Gotta do it this way unfortunately.
